Upgrade Numpy and Pandas (to last version which passes tests)
There's a dependency here which means that upgrading them individually
doesn't work.

The next release of Pandas [1.3.0][link] breaks exactly one test:
```
======================================================================
FAIL: test_practice_statistics_measure (frontend.tests.commands.test_import_measures.ImportMeasuresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_import_measures.py", line 156, in test_practice_statistics_measure
    self.validate_calculations(
  File "/code/openprescribing/frontend/tests/commands/test_import_measures.py", line 315, in validate_calculations
    self.validate_measure_value(mv, pcns.loc[mv.pcn_id])
  File "/code/openprescribing/frontend/tests/commands/test_import_measures.py", line 375, in validate_measure_value
    self.assertAlmostEqual(mv.percentile, series["ratio_percentile"])
AssertionError: 18.5483870967742 != 19.35483870967742 within 7 places (0.8064516129032206 difference)
```

[link]: https://pandas.pydata.org/docs/whatsnew/v1.3.0.html